#!/usr/bin/env python
# coding=utf-8

#Imports necesarios
import argparse
import sys


#Definicion de argumentos y pasaje de parametros.

parser = argparse.ArgumentParser(description="Compilador de Pascal Reducido", epilog="Compilador para Pascal Reducido desarrollado en Python para las materias de Diseño de Compiladores e Interpretes y Laboratorio de Compiladores e Interpretes. \n Facultad de Informatica - Universidad Nacional del Comahue. \n Distribuido bajo licencia GNUv3. https://github.com/Jmdelafuente22/CeI")
parser.add_argument("archivo", metavar='archivo.pas' ,help="Ruta relativa del fichero a analizar sintacticamente.", type=str)
parser.add_argument("-verbose_mode","-v", help="Flag para modo Verboso con impresiones de control.",action='store_true')
parser.add_argument("-standalone","-s", help="Flag para funcionamiento por separado del aplicativo.",action='store_true')
args = parser.parse_args()

archivo= args.archivo
verboso= args.verbose_mode

#Llamada al analizador Lexico
if(verboso):
	sys.argv = ['analizadorLexico.py',archivo,'-v']
else:
	sys.argv = ['analizadorLexico.py',archivo]
execfile('analizadorLexico.py')
#print tokens
#LLamada al analizador Sintactico
if(verboso):
	sys.argv = ['analizadorSintactico.py',archivo,'-v']
else:
	sys.argv = ['analizadorSintactico.py',archivo]

execfile('analizadorSintactico.py')
